[package]
name = "auth_server"
version = "0.1.0"
authors = ["Michael Riezler <michael@riezler.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
include_dir = "0.6.0"
clap = "3.0.0-beta.2"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
features = ["postgres_pool"]

[dependencies.postgres]
version = "0.18.1"
features = ["with-uuid-0_8"]